# Generated by Django 4.2.6 on 2023-11-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=1, verbose_name='address'),
            preserve_default=False,
        ),
    ]
